function [exx,eyy,exy] = Dis2Strain(meshInfo,locJ,detJ,dNds,dNdt,ux,uy)
	%%%===========================Description================================%%%
	%%% This is a function to calculate strain values at strain points per
    %%% element from diplacement data.
	%%%======================================================================%%%
    uxEle = num2cell(ux(meshInfo.eleNodsID),1);
    uyEle = num2cell(uy(meshInfo.eleNodsID),1);
    detJ = cell2mat(detJ);
    exx = cellfun(@(dNds,dNdt,uxEle) ...
        ((locJ{1} .* dNds + locJ{2} .* dNdt) ./ detJ) .* uxEle, ...
        dNds,dNdt,uxEle,'UniformOutput',false);
    eyy = cellfun(@(dNds,dNdt,uyEle) ...
        ((locJ{3} .* dNds + locJ{4} .* dNdt) ./ detJ) .* uyEle, ...
        dNds,dNdt,uyEle,'UniformOutput',false);
    exy = cellfun(@(dNds,dNdt,uxEle,uyEle) ...
        ((locJ{3} .* dNds + locJ{4} .* dNdt) .* uxEle + ...
         (locJ{1} .* dNds + locJ{2} .* dNdt) .* uyEle) ./ detJ, ...
        dNds,dNdt,uxEle,uyEle,'UniformOutput',false);
    exx = exx{1} + exx{2} + exx{3} + exx{4};
    eyy = eyy{1} + eyy{2} + eyy{3} + eyy{4};
    exy = exy{1} + exy{2} + exy{3} + exy{4};
end