"""Run the fixed-data multi-seed reproducibility experiment."""

from __future__ import annotations

import argparse
import shutil
import sys
from collections import OrderedDict
from pathlib import Path

import torch


CURRENT_DIR = Path(__file__).resolve().parent
IGFE_ROOT = CURRENT_DIR.parent
PROJECT_ROOT = IGFE_ROOT.parent
if str(IGFE_ROOT) not in sys.path:
    sys.path.insert(0, str(IGFE_ROOT))

from model.train import Training
from postprocess.reproducibility import (
    evaluate_checkpoint,
    plot_seed_reproducibility,
    write_cross_seed_summary,
    write_paired_comparison,
    write_per_sample_metrics,
    write_seed_summary,
)
from utils.reproducibility import (
    resolve_project_path,
    seed_everything,
    sha256_file,
    write_json,
)
from utils.utils_process import Config
from utils.utils_test import fixed_test_set_exists


METHODS = OrderedDict(
    [
        ("MSE-M", {"method": "MSE", "gamma": None}),
        ("LM-M", {"method": "LocMixloss", "gamma": 100000}),
        ("GM-M", {"method": "GloMixloss", "gamma": 10000}),
    ]
)
DEFAULT_SEEDS = [7, 17, 27, 37, 42, 47, 123, 2024, 2025, 3407]


def make_config(args, model_name, seed, model_dir, data_dir):
    """Build one experiment config without changing the formal config files."""
    spec = METHODS[model_name]
    cfg = Config("mix")
    cfg.config_type = "mix"
    cfg.dataset_type = "mix"
    cfg.data_path = str(data_dir)
    cfg.fixed_test_data_dir_override = str(args.fixed_test_dir)
    cfg.device = args.device if args.device != "auto" else cfg.device
    cfg.method = spec["method"]
    if spec["gamma"] is not None:
        cfg.gamma = float(args.gamma_loc if model_name == "LM-M" else args.gamma_glo)
    cfg.seed = int(seed)
    cfg.data_order_seed = int(args.data_order_seed)
    cfg.num_workers = int(args.num_workers)
    cfg.pin_memory = False
    cfg.preload = False
    cfg.num = "all"
    cfg.eval_split = "test"
    cfg.eval_types = ["mix"]
    cfg.noise_level = 0.0
    cfg.noise_levels = [0]
    cfg.experiment_group = "std" if spec["gamma"] is None else "gamma"
    cfg.experiment_dir_override = str(model_dir)
    cfg.exp_id_override = f"{model_name}_seed_{int(seed)}"

    if args.epochs is not None:
        cfg.n_epochs = int(args.epochs)
    if args.batch_size is not None:
        cfg.batch_size = int(args.batch_size)
    return cfg


def required_split_files(model_names):
    """Return files required by the selected trainers in train/val."""
    required = {
        "train": {"input.mat", "output.mat"},
        "val": {"input.mat", "output.mat"},
    }
    if any(METHODS[name]["method"] != "MSE" for name in model_names):
        for split in required:
            required[split].update({"dof.npy", "force_ele.npy", "force.npy"})
    return required


def find_training_manifest(data_dir):
    """Locate the immutable manifest generated by data_process.py."""
    candidates = [
        data_dir / "dataset_manifest.json",
        data_dir / "manifest.json",
        data_dir.parent / "dataset_manifest.json",
    ]
    return next((path for path in candidates if path.is_file()), None)


def validate_inputs(args, model_names, data_dir):
    """Validate fixed train/val files and the fixed public test manifest."""
    missing = []
    for split, filenames in required_split_files(model_names).items():
        split_dir = data_dir / split
        missing.extend(
            str(split_dir / filename)
            for filename in filenames
            if not (split_dir / filename).is_file()
        )
    if missing:
        raise FileNotFoundError(
            "Training data is incomplete. Expected an immutable data_process.py "
            "output with train/val splits; missing:\n  - " + "\n  - ".join(missing)
        )

    validation_cfg = make_config(
        args, model_names[0], args.seeds[0], data_dir / "_validation", data_dir
    )
    if not fixed_test_set_exists(validation_cfg):
        raise FileNotFoundError(
            "The fixed public test set is missing or incomplete: "
            f"{args.fixed_test_dir}"
        )
    fixed_manifest = args.fixed_test_dir.parent / "manifest.json"
    if not fixed_manifest.is_file():
        raise FileNotFoundError(f"Fixed test manifest not found: {fixed_manifest}")

    training_manifest = find_training_manifest(data_dir)
    if training_manifest is None and not args.allow_missing_train_manifest:
        raise FileNotFoundError(
            f"Training dataset manifest not found under {data_dir}. "
            "Use --allow-missing-train-manifest only after independent verification."
        )
    return training_manifest, fixed_manifest


def protocol_metadata(args, data_dir, training_manifest, fixed_manifest, cfg):
    """Build the protocol record copied alongside all experiment outputs."""
    return {
        "protocol": "reviewer4#9_multi_seed_reproducibility",
        "config_type": "mix",
        "methods": {
            name: {
                "internal_method": METHODS[name]["method"],
                "gamma": None if METHODS[name]["gamma"] is None else float(
                    args.gamma_loc if name == "LM-M" else args.gamma_glo
                ),
            }
            for name in args.methods
        },
        "initialization_seeds": [int(seed) for seed in args.seeds],
        "data_order_seed": int(args.data_order_seed),
        "data_dir": str(data_dir),
        "training_manifest": str(training_manifest) if training_manifest else None,
        "training_manifest_sha256": sha256_file(training_manifest) if training_manifest else None,
        "fixed_test_dir": str(args.fixed_test_dir),
        "fixed_test_manifest": str(fixed_manifest),
        "fixed_test_manifest_sha256": sha256_file(fixed_manifest),
        "architecture": {
            "filters_list": cfg.filters_list,
            "kernel_size": cfg.kernel_size,
            "use_batch_norm": cfg.use_batch_norm,
        },
        "train_rto": cfg.train_rto,
        "valid_rto": cfg.valid_rto,
        "noise_level_percent": 0.0,
        "device": cfg.device,
        "num_workers": int(args.num_workers),
        "torch_version": torch.__version__,
    }


def prepare_output(args, data_dir, training_manifest, fixed_manifest, reference_cfg):
    """Create the independent reproducibility output tree and metadata."""
    output_root = resolve_project_path(args.output_root, PROJECT_ROOT)
    output_root.mkdir(parents=True, exist_ok=True)
    for subdir in ("configs", "models", "metrics", "figures"):
        (output_root / subdir).mkdir(exist_ok=True)

    fixed_copy = output_root / "configs" / "fixed_test_manifest.json"
    if fixed_copy.exists() and not args.overwrite:
        if sha256_file(fixed_copy) != sha256_file(fixed_manifest):
            raise FileExistsError(f"Existing fixed test manifest differs: {fixed_copy}")
    elif args.overwrite or not fixed_copy.exists():
        shutil.copy2(fixed_manifest, fixed_copy)

    if training_manifest:
        training_copy = output_root / "configs" / "training_dataset_manifest.json"
        if args.overwrite or not training_copy.exists():
            shutil.copy2(training_manifest, training_copy)

    write_json(
        output_root / "configs" / "protocol.json",
        protocol_metadata(args, data_dir, training_manifest, fixed_manifest, reference_cfg),
    )
    return output_root


def run_experiment(cfg, checkpoint_path, eval_batch_size):
    """Train one seed and evaluate its checkpoint on the fixed test set."""
    model_dir = Path(cfg.experiment_dir_override)
    model_dir.mkdir(parents=True, exist_ok=True)
    print(f"Training {cfg.method}, initialization seed={cfg.seed}")
    seed_everything(cfg.seed)
    Training(cfg).run_train()
    if not checkpoint_path.is_file():
        raise FileNotFoundError(f"Training completed without checkpoint: {checkpoint_path}")
    return evaluate_checkpoint(cfg, checkpoint_path, eval_batch_size)


def run_reproducibility(args):
    """Execute all requested model/seed runs and write the summaries."""
    args.fixed_test_dir = resolve_project_path(args.fixed_test_dir, PROJECT_ROOT)
    args.methods = list(args.methods)
    data_dir = resolve_project_path(
        args.data_dir or "data/data_mix/force_load", PROJECT_ROOT
    )
    unknown = [name for name in args.methods if name not in METHODS]
    if unknown:
        raise ValueError(f"Unknown model label(s): {unknown}")

    training_manifest, fixed_manifest = validate_inputs(args, args.methods, data_dir)
    reference_cfg = make_config(
        args, args.methods[0], args.seeds[0], data_dir / "_reference", data_dir
    )
    output_root = prepare_output(
        args, data_dir, training_manifest, fixed_manifest, reference_cfg
    )

    results = OrderedDict()
    for model_name in args.methods:
        for seed in args.seeds:
            model_dir = output_root / "models" / model_name / f"seed_{int(seed)}"
            checkpoint_path = model_dir / "model.pt"
            if model_dir.exists() and any(model_dir.iterdir()) and not args.overwrite:
                raise FileExistsError(
                    f"Refusing to overwrite existing run: {model_dir}. "
                    "Use a new output root or --overwrite."
                )

            cfg = make_config(args, model_name, seed, model_dir, data_dir)
            write_json(
                output_root / "configs" / f"{model_name}_seed_{int(seed)}.json",
                {
                    "model": model_name,
                    "seed": int(seed),
                    "data_order_seed": int(args.data_order_seed),
                    "internal_method": cfg.method,
                    "gamma": getattr(cfg, "gamma", None),
                    "data_path": str(data_dir),
                    "fixed_test_data_dir": str(args.fixed_test_dir),
                    "filters_list": cfg.filters_list,
                    "kernel_size": cfg.kernel_size,
                    "use_batch_norm": cfg.use_batch_norm,
                    "n_epochs": cfg.n_epochs,
                    "batch_size": cfg.batch_size,
                    "train_rto": cfg.train_rto,
                    "valid_rto": cfg.valid_rto,
                    "num_workers": cfg.num_workers,
                },
            )
            rows = run_experiment(cfg, checkpoint_path, args.eval_batch_size)
            results[(model_name, int(seed))] = rows
            write_per_sample_metrics(
                output_root / "metrics" / f"per_sample_{model_name}_seed_{int(seed)}.csv",
                model_name,
                seed,
                rows,
            )

    write_seed_summary(output_root / "metrics" / "seed_summary.csv", results)
    write_cross_seed_summary(output_root / "metrics" / "cross_seed_summary.csv", results)
    write_paired_comparison(output_root / "metrics" / "paired_lm_vs_gm.csv", results)
    plot_seed_reproducibility(
        output_root / "figures" / "seed_reproducibility.png",
        output_root / "figures" / "seed_reproducibility.pdf",
        results,
    )
    print(f"Reproducibility outputs written to: {output_root}")


def parse_args(argv=None):
    """Parse command-line options for the direct script invocation."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--methods", nargs="+", choices=list(METHODS), default=list(METHODS))
    parser.add_argument("--seeds", nargs="+", type=int, default=DEFAULT_SEEDS)
    parser.add_argument("--data-dir", default=None)
    parser.add_argument(
        "--fixed-test-dir",
        default="data/fixed_test_sets/force_load/data_mix",
    )
    parser.add_argument("--output-root", default="results/reproducibility")
    parser.add_argument("--device", choices=["auto", "cpu", "cuda", "mps"], default="auto")
    parser.add_argument("--epochs", type=int, default=None)
    parser.add_argument("--batch-size", type=int, default=None)
    parser.add_argument("--eval-batch-size", type=int, default=32)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--data-order-seed", type=int, default=42)
    parser.add_argument("--gamma-loc", type=float, default=100000)
    parser.add_argument("--gamma-glo", type=float, default=10000)
    parser.add_argument("--allow-missing-train-manifest", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args(argv)


args = parse_args()
run_reproducibility(args)
